create schema if not exists geographic;
---------------------------------------------------------------------------------------------------------
drop table geographic.continent;
CREATE TABLE GEOGRAPHIC.continent (
	continent_id varchar(2) PRIMARY KEY,
	continent varchar(50) NOT NULL,
	is_active boolean NOT null default TRUE,
	sort int,
	usrcrt varchar(30),
	dtmcrt timestamp,
	usrupd varchar(30),
	dtmupd timestamp
);

insert into GEOGRAPHIC.continent (continent_id, continent, sort, usrcrt, dtmcrt, usrupd, dtmupd)
values
	('AS', 'Asia', 1, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
	('AF', 'Africa', 1, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
	('EU', 'Europe', 1, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
	('NA', 'North America', 1, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
	('SA', 'South America', 1, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
	('OC', 'Oceania', 1, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
	('AN', 'Antarctica', 1, 'SYSTEM', NOW(), 'SYSTEM', NOW())
	;
	
select * from geographic.continent;
---------------------------------------------------------------------------------------------------------
drop table geographic.country;
CREATE TABLE GEOGRAPHIC.country (
	Country_Code_2 varchar(2) PRIMARY KEY,
	Country_Code_3 varchar(3),
	Country varchar(100) NOT NULL,
	continent_code varchar(2) REFERENCES geographic.continent(continent_id) on delete restrict on update restrict,
	is_active boolean NOT null default TRUE,
	sort int,
	usrcrt varchar(30),
	dtmcrt timestamp,
	usrupd varchar(30),
	dtmupd timestamp
);

insert into GEOGRAPHIC.country(continent_code, Country, Country_Code_2, Country_Code_3, sort, usrcrt, dtmcrt, usrupd, dtmupd)
values 
('AS', 'Afghanistan, Islamic Republic of', 'AF', 'AFG', 4, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('EU', 'Albania, Republic of', 'AL', 'ALB', 8, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('AN', 'Antarctica (the territory South of 60 deg S)', 'AQ', 'ATA', 10, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('AF', 'Algeria, People''s Democratic Republic of', 'DZ', 'DZA', 12, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('OC', 'American Samoa', 'AS', 'ASM', 16, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('EU', 'Andorra, Principality of', 'AD', 'AND', 20, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('AF', 'Angola, Republic of', 'AO', 'AGO', 24, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('NA', 'Antigua and Barbuda', 'AG', 'ATG', 28, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('EU', 'Azerbaijan, Republic of', 'AZ', 'AZE', 31, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('SA', 'Argentina, Argentine Republic', 'AR', 'ARG', 32, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('OC', 'Australia, Commonwealth of', 'AU', 'AUS', 36, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('EU', 'Austria, Republic of', 'AT', 'AUT', 40, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('NA', 'Bahamas, Commonwealth of the', 'BS', 'BHS', 44, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('AS', 'Bahrain, Kingdom of', 'BH', 'BHR', 48, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('AS', 'Bangladesh, People''s Republic of', 'BD', 'BGD', 50, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('EU', 'Armenia, Republic of', 'AM', 'ARM', 51, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('NA', 'Barbados', 'BB', 'BRB', 52, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('EU', 'Belgium, Kingdom of', 'BE', 'BEL', 56, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('NA', 'Bermuda', 'BM', 'BMU', 60, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('AS', 'Bhutan, Kingdom of', 'BT', 'BTN', 64, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('SA', 'Bolivia, Republic of', 'BO', 'BOL', 68, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('EU', 'Bosnia and Herzegovina', 'BA', 'BIH', 70, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('AF', 'Botswana, Republic of', 'BW', 'BWA', 72, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('AN', 'Bouvet Island (Bouvetoya)', 'BV', 'BVT', 74, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('SA', 'Brazil, Federative Republic of', 'BR', 'BRA', 76, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('NA', 'Belize', 'BZ', 'BLZ', 84, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('AS', 'British Indian Ocean Territory (Chagos Archipelago)', 'IO', 'IOT', 86, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('OC', 'Solomon Islands', 'SB', 'SLB', 90, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('NA', 'British Virgin Islands', 'VG', 'VGB', 92, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('AS', 'Brunei Darussalam', 'BN', 'BRN', 96, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('EU', 'Bulgaria, Republic of', 'BG', 'BGR', 100, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('AS', 'Myanmar, Union of', 'MM', 'MMR', 104, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('AF', 'Burundi, Republic of', 'BI', 'BDI', 108, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('EU', 'Belarus, Republic of', 'BY', 'BLR', 112, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('AS', 'Cambodia, Kingdom of', 'KH', 'KHM', 116, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('AF', 'Cameroon, Republic of', 'CM', 'CMR', 120, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('NA', 'Canada', 'CA', 'CAN', 124, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('AF', 'Cape Verde, Republic of', 'CV', 'CPV', 132, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('NA', 'Cayman Islands', 'KY', 'CYM', 136, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('AF', 'Central African Republic', 'CF', 'CAF', 140, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('AS', 'Sri Lanka, Democratic Socialist Republic of', 'LK', 'LKA', 144, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('AF', 'Chad, Republic of', 'TD', 'TCD', 148, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('SA', 'Chile, Republic of', 'CL', 'CHL', 152, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('AS', 'China, People''s Republic of', 'CN', 'CHN', 156, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('AS', 'Taiwan', 'TW', 'TWN', 158, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('AS', 'Christmas Island', 'CX', 'CXR', 162, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('AS', 'Cocos (Keeling) Islands', 'CC', 'CCK', 166, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('SA', 'Colombia, Republic of', 'CO', 'COL', 170, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('AF', 'Comoros, Union of the', 'KM', 'COM', 174, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('AF', 'Mayotte', 'YT', 'MYT', 175, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('AF', 'Congo, Republic of the', 'CG', 'COG', 178, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('AF', 'Congo, Democratic Republic of the', 'CD', 'COD', 180, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('OC', 'Cook Islands', 'CK', 'COK', 184, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('NA', 'Costa Rica, Republic of', 'CR', 'CRI', 188, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('EU', 'Croatia, Republic of', 'HR', 'HRV', 191, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('NA', 'Cuba, Republic of', 'CU', 'CUB', 192, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('EU', 'Cyprus, Republic of', 'CY', 'CYP', 196, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('EU', 'Czech Republic', 'CZ', 'CZE', 203, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('AF', 'Benin, Republic of', 'BJ', 'BEN', 204, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('EU', 'Denmark, Kingdom of', 'DK', 'DNK', 208, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('NA', 'Dominica, Commonwealth of', 'DM', 'DMA', 212, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('NA', 'Dominican Republic', 'DO', 'DOM', 214, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('SA', 'Ecuador, Republic of', 'EC', 'ECU', 218, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('NA', 'El Salvador, Republic of', 'SV', 'SLV', 222, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('AF', 'Equatorial Guinea, Republic of', 'GQ', 'GNQ', 226, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('AF', 'Ethiopia, Federal Democratic Republic of', 'ET', 'ETH', 231, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('AF', 'Eritrea, State of', 'ER', 'ERI', 232, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('EU', 'Estonia, Republic of', 'EE', 'EST', 233, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('EU', 'Faroe Islands', 'FO', 'FRO', 234, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('SA', 'Falkland Islands (Malvinas)', 'FK', 'FLK', 238, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('AN', 'South Georgia and the South Sandwich Islands', 'GS', 'SGS', 239, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('OC', 'Fiji, Republic of the Fiji Islands', 'FJ', 'FJI', 242, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('EU', 'Finland, Republic of', 'FI', 'FIN', 246, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('EU', 'Åland Islands', 'AX', 'ALA', 248, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('EU', 'France, French Republic', 'FR', 'FRA', 250, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('SA', 'French Guiana', 'GF', 'GUF', 254, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('OC', 'French Polynesia', 'PF', 'PYF', 258, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('AN', 'French Southern Territories', 'TF', 'ATF', 260, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('AF', 'Djibouti, Republic of', 'DJ', 'DJI', 262, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('AF', 'Gabon, Gabonese Republic', 'GA', 'GAB', 266, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('EU', 'Georgia', 'GE', 'GEO', 268, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('AF', 'Gambia, Republic of the', 'GM', 'GMB', 270, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('AS', 'Palestinian Territory, Occupied', 'PS', 'PSE', 275, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('EU', 'Germany, Federal Republic of', 'DE', 'DEU', 276, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('AF', 'Ghana, Republic of', 'GH', 'GHA', 288, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('EU', 'Gibraltar', 'GI', 'GIB', 292, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('OC', 'Kiribati, Republic of', 'KI', 'KIR', 296, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('EU', 'Greece, Hellenic Republic', 'GR', 'GRC', 300, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('NA', 'Greenland', 'GL', 'GRL', 304, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('NA', 'Grenada', 'GD', 'GRD', 308, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('NA', 'Guadeloupe', 'GP', 'GLP', 312, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('OC', 'Guam', 'GU', 'GUM', 316, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('NA', 'Guatemala, Republic of', 'GT', 'GTM', 320, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('AF', 'Guinea, Republic of', 'GN', 'GIN', 324, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('SA', 'Guyana, Co-operative Republic of', 'GY', 'GUY', 328, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('NA', 'Haiti, Republic of', 'HT', 'HTI', 332, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('AN', 'Heard Island and McDonald Islands', 'HM', 'HMD', 334, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('EU', 'Holy See (Vatican City State)', 'VA', 'VAT', 336, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('NA', 'Honduras, Republic of', 'HN', 'HND', 340, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('AS', 'Hong Kong, Special Administrative Region of China', 'HK', 'HKG', 344, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('EU', 'Hungary, Republic of', 'HU', 'HUN', 348, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('EU', 'Iceland, Republic of', 'IS', 'ISL', 352, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('AS', 'India, Republic of', 'IN', 'IND', 356, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('AS', 'Indonesia, Republic of', 'ID', 'IDN', 360, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('AS', 'Iran, Islamic Republic of', 'IR', 'IRN', 364, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('AS', 'Iraq, Republic of', 'IQ', 'IRQ', 368, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('EU', 'Ireland', 'IE', 'IRL', 372, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('AS', 'Israel, State of', 'IL', 'ISR', 376, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('EU', 'Italy, Italian Republic', 'IT', 'ITA', 380, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('AF', 'Cote d''Ivoire, Republic of', 'CI', 'CIV', 384, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('NA', 'Jamaica', 'JM', 'JAM', 388, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('AS', 'Japan', 'JP', 'JPN', 392, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('AS', 'Kazakhstan, Republic of', 'KZ', 'KAZ', 398, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('AS', 'Jordan, Hashemite Kingdom of', 'JO', 'JOR', 400, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('AF', 'Kenya, Republic of', 'KE', 'KEN', 404, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('AS', 'Korea, Democratic People''s Republic of', 'KP', 'PRK', 408, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('AS', 'Korea, Republic of', 'KR', 'KOR', 410, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('AS', 'Kuwait, State of', 'KW', 'KWT', 414, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('AS', 'Kyrgyz Republic', 'KG', 'KGZ', 417, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('AS', 'Lao People''s Democratic Republic', 'LA', 'LAO', 418, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('AS', 'Lebanon, Lebanese Republic', 'LB', 'LBN', 422, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('AF', 'Lesotho, Kingdom of', 'LS', 'LSO', 426, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('EU', 'Latvia, Republic of', 'LV', 'LVA', 428, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('AF', 'Liberia, Republic of', 'LR', 'LBR', 430, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('AF', 'Libyan Arab Jamahiriya', 'LY', 'LBY', 434, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('EU', 'Liechtenstein, Principality of', 'LI', 'LIE', 438, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('EU', 'Lithuania, Republic of', 'LT', 'LTU', 440, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('EU', 'Luxembourg, Grand Duchy of', 'LU', 'LUX', 442, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('AS', 'Macao, Special Administrative Region of China', 'MO', 'MAC', 446, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('AF', 'Madagascar, Republic of', 'MG', 'MDG', 450, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('AF', 'Malawi, Republic of', 'MW', 'MWI', 454, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('AS', 'Malaysia', 'MY', 'MYS', 458, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('AS', 'Maldives, Republic of', 'MV', 'MDV', 462, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('AF', 'Mali, Republic of', 'ML', 'MLI', 466, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('EU', 'Malta, Republic of', 'MT', 'MLT', 470, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('NA', 'Martinique', 'MQ', 'MTQ', 474, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('AF', 'Mauritania, Islamic Republic of', 'MR', 'MRT', 478, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('AF', 'Mauritius, Republic of', 'MU', 'MUS', 480, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('NA', 'Mexico, United Mexican States', 'MX', 'MEX', 484, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('EU', 'Monaco, Principality of', 'MC', 'MCO', 492, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('AS', 'Mongolia', 'MN', 'MNG', 496, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('EU', 'Moldova, Republic of', 'MD', 'MDA', 498, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('EU', 'Montenegro, Republic of', 'ME', 'MNE', 499, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('NA', 'Montserrat', 'MS', 'MSR', 500, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('AF', 'Morocco, Kingdom of', 'MA', 'MAR', 504, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('AF', 'Mozambique, Republic of', 'MZ', 'MOZ', 508, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('AS', 'Oman, Sultanate of', 'OM', 'OMN', 512, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('AF', 'Namibia, Republic of', 'NA', 'NAM', 516, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('OC', 'Nauru, Republic of', 'NR', 'NRU', 520, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('AS', 'Nepal, State of', 'NP', 'NPL', 524, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('EU', 'Netherlands, Kingdom of the', 'NL', 'NLD', 528, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('NA', 'Netherlands Antilles', 'AN', 'ANT', 530, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('NA', 'Curaçao', 'CW', 'CUW', 531, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('NA', 'Aruba', 'AW', 'ABW', 533, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('NA', 'Sint Maarten (Netherlands)', 'SX', 'SXM', 534, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('NA', 'Bonaire, Sint Eustatius and Saba', 'BQ', 'BES', 535, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('OC', 'New Caledonia', 'NC', 'NCL', 540, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('OC', 'Vanuatu, Republic of', 'VU', 'VUT', 548, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('OC', 'New Zealand', 'NZ', 'NZL', 554, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('NA', 'Nicaragua, Republic of', 'NI', 'NIC', 558, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('AF', 'Niger, Republic of', 'NE', 'NER', 562, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('AF', 'Nigeria, Federal Republic of', 'NG', 'NGA', 566, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('OC', 'Niue', 'NU', 'NIU', 570, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('OC', 'Norfolk Island', 'NF', 'NFK', 574, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('EU', 'Norway, Kingdom of', 'NO', 'NOR', 578, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('OC', 'Northern Mariana Islands, Commonwealth of the', 'MP', 'MNP', 580, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('OC', 'United States Minor Outlying Islands', 'UM', 'UMI', 581, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('OC', 'Micronesia, Federated States of', 'FM', 'FSM', 583, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('OC', 'Marshall Islands, Republic of the', 'MH', 'MHL', 584, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('OC', 'Palau, Republic of', 'PW', 'PLW', 585, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('AS', 'Pakistan, Islamic Republic of', 'PK', 'PAK', 586, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('NA', 'Panama, Republic of', 'PA', 'PAN', 591, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('OC', 'Papua New Guinea, Independent State of', 'PG', 'PNG', 598, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('SA', 'Paraguay, Republic of', 'PY', 'PRY', 600, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('SA', 'Peru, Republic of', 'PE', 'PER', 604, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('AS', 'Philippines, Republic of the', 'PH', 'PHL', 608, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('OC', 'Pitcairn Islands', 'PN', 'PCN', 612, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('EU', 'Poland, Republic of', 'PL', 'POL', 616, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('EU', 'Portugal, Portuguese Republic', 'PT', 'PRT', 620, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('AF', 'Guinea-Bissau, Republic of', 'GW', 'GNB', 624, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('AS', 'Timor-Leste, Democratic Republic of', 'TL', 'TLS', 626, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('NA', 'Puerto Rico, Commonwealth of', 'PR', 'PRI', 630, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('AS', 'Qatar, State of', 'QA', 'QAT', 634, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('AF', 'Reunion', 'RE', 'REU', 638, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('EU', 'Romania', 'RO', 'ROU', 642, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('EU', 'Russian Federation', 'RU', 'RUS', 643, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('AF', 'Rwanda, Republic of', 'RW', 'RWA', 646, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('NA', 'Saint Barthelemy', 'BL', 'BLM', 652, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('AF', 'Saint Helena', 'SH', 'SHN', 654, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('NA', 'Saint Kitts and Nevis, Federation of', 'KN', 'KNA', 659, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('NA', 'Anguilla', 'AI', 'AIA', 660, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('NA', 'Saint Lucia', 'LC', 'LCA', 662, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('NA', 'Saint Martin', 'MF', 'MAF', 663, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('NA', 'Saint Pierre and Miquelon', 'PM', 'SPM', 666, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('NA', 'Saint Vincent and the Grenadines', 'VC', 'VCT', 670, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('EU', 'San Marino, Republic of', 'SM', 'SMR', 674, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('AF', 'Sao Tome and Principe, Democratic Republic of', 'ST', 'STP', 678, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('AS', 'Saudi Arabia, Kingdom of', 'SA', 'SAU', 682, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('AF', 'Senegal, Republic of', 'SN', 'SEN', 686, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('EU', 'Serbia, Republic of', 'RS', 'SRB', 688, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('AF', 'Seychelles, Republic of', 'SC', 'SYC', 690, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('AF', 'Sierra Leone, Republic of', 'SL', 'SLE', 694, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('AS', 'Singapore, Republic of', 'SG', 'SGP', 702, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('EU', 'Slovakia (Slovak Republic)', 'SK', 'SVK', 703, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('AS', 'Vietnam, Socialist Republic of', 'VN', 'VNM', 704, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('EU', 'Slovenia, Republic of', 'SI', 'SVN', 705, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('AF', 'Somalia, Somali Republic', 'SO', 'SOM', 706, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('AF', 'South Africa, Republic of', 'ZA', 'ZAF', 710, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('AF', 'Zimbabwe, Republic of', 'ZW', 'ZWE', 716, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('EU', 'Spain, Kingdom of', 'ES', 'ESP', 724, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('AF', 'South Sudan', 'SS', 'SSD', 728, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('AF', 'Western Sahara', 'EH', 'ESH', 732, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('AF', 'Sudan, Republic of', 'SD', 'SDN', 736, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('SA', 'Suriname, Republic of', 'SR', 'SUR', 740, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('EU', 'Svalbard & Jan Mayen Islands', 'SJ', 'SJM', 744, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('AF', 'Swaziland, Kingdom of', 'SZ', 'SWZ', 748, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('EU', 'Sweden, Kingdom of', 'SE', 'SWE', 752, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('EU', 'Switzerland, Swiss Confederation', 'CH', 'CHE', 756, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('AS', 'Syrian Arab Republic', 'SY', 'SYR', 760, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('AS', 'Tajikistan, Republic of', 'TJ', 'TJK', 762, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('AS', 'Thailand, Kingdom of', 'TH', 'THA', 764, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('AF', 'Togo, Togolese Republic', 'TG', 'TGO', 768, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('OC', 'Tokelau', 'TK', 'TKL', 772, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('OC', 'Tonga, Kingdom of', 'TO', 'TON', 776, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('NA', 'Trinidad and Tobago, Republic of', 'TT', 'TTO', 780, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('AS', 'United Arab Emirates', 'AE', 'ARE', 784, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('AF', 'Tunisia, Tunisian Republic', 'TN', 'TUN', 788, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('EU', 'Turkey, Republic of', 'TR', 'TUR', 792, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('AS', 'Turkmenistan', 'TM', 'TKM', 795, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('NA', 'Turks and Caicos Islands', 'TC', 'TCA', 796, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('OC', 'Tuvalu', 'TV', 'TUV', 798, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('AF', 'Uganda, Republic of', 'UG', 'UGA', 800, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('EU', 'Ukraine', 'UA', 'UKR', 804, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('EU', 'Macedonia, The Former Yugoslav Republic of', 'MK', 'MKD', 807, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('AF', 'Egypt, Arab Republic of', 'EG', 'EGY', 818, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('EU', 'United Kingdom of Great Britain & Northern Ireland', 'GB', 'GBR', 826, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('EU', 'Guernsey, Bailiwick of', 'GG', 'GGY', 831, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('EU', 'Jersey, Bailiwick of', 'JE', 'JEY', 832, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('EU', 'Isle of Man', 'IM', 'IMN', 833, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('AF', 'Tanzania, United Republic of', 'TZ', 'TZA', 834, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('NA', 'United States of America', 'US', 'USA', 840, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('NA', 'United States Virgin Islands', 'VI', 'VIR', 850, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('AF', 'Burkina Faso', 'BF', 'BFA', 854, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('SA', 'Uruguay, Eastern Republic of', 'UY', 'URY', 858, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('AS', 'Uzbekistan, Republic of', 'UZ', 'UZB', 860, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('SA', 'Venezuela, Bolivarian Republic of', 'VE', 'VEN', 862, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('OC', 'Wallis and Futuna', 'WF', 'WLF', 876, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('OC', 'Samoa, Independent State of', 'WS', 'WSM', 882, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('AS', 'Yemen', 'YE', 'YEM', 887, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('AF', 'Zambia, Republic of', 'ZM', 'ZMB', 894, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('OC', 'Disputed Territory', 'XX', '', null, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('AS', 'Iraq-Saudi Arabia Neutral Zone', 'XE', '', null, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('AS', 'United Nations Neutral Zone', 'XD', '', null, 'SYSTEM', NOW(), 'SYSTEM', NOW()),
('AS', 'Spratly Islands', 'XS', '',  null, 'SYSTEM', NOW(), 'SYSTEM', NOW())
;

select * from geographic.country;
---------------------------------------------------------------------------------------------------------
